import { requireEditorAuth } from "@/lib/api-auth";
import { canEditProject, getProjectPrincipal, principalRequiredResponse, projectAccessResponse } from "@/lib/project-access";
import { getProject } from "@/lib/projects";
import { listRuntimeUpgradesForProject, startRuntimeUpgrade, RuntimeUpgradeStoreError } from "@/lib/runtime-upgrade-manager.mjs";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
export async function GET(request: Request, context: { params: Promise<{ id: string }> }) { try { const access = await authorize(request, context); if (access.response) return access.response; return Response.json(await listRuntimeUpgradesForProject(access.project), { headers: { "Cache-Control": "no-store" } }); } catch (error) { return errorResponse(error, "Unable to list runtime upgrades."); } }
export async function POST(request: Request, context: { params: Promise<{ id: string }> }) { try { const access = await authorize(request, context); if (access.response) return access.response; const body = await request.json().catch(() => ({})); return Response.json({ upgrade: await startRuntimeUpgrade(access.project, body.runtimeVersion) }, { status: 201 }); } catch (error) { return errorResponse(error, "Unable to start runtime upgrade."); } }
async function authorize(request: Request, context: { params: Promise<{ id: string }> }) { const auth = await requireEditorAuth(request); if (auth) return { response: auth }; const principal = getProjectPrincipal(request); if (!principal) return { response: principalRequiredResponse() }; const { id } = await context.params; const project = await getProject(id); if (!project || project.status === "deleted") return { response: Response.json({ error: "Project was not found." }, { status: 404 }) }; if (!canEditProject(project, principal)) return { response: projectAccessResponse() }; return { project }; }
function errorResponse(error: unknown, fallback: string) { const status = error instanceof RuntimeUpgradeStoreError ? error.status : 500; return Response.json({ error: error instanceof Error ? error.message : fallback }, { status }); }
