import { requireEditorAuth } from "@/lib/api-auth";
import { canEditProject, getProjectPrincipal, principalRequiredResponse, projectAccessResponse } from "@/lib/project-access";
import { getProject } from "@/lib/projects";
import { acceptStoredRuntimeUpgrade, cancelStoredRuntimeUpgrade, getRuntimeUpgradeForProject, RuntimeUpgradeStoreError } from "@/lib/runtime-upgrade-manager.mjs";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
export async function GET(request: Request, context: { params: Promise<{ id: string; upgradeId: string }> }) { try { const access = await authorize(request, context); if (access.response) return access.response; const { upgradeId } = await context.params; return Response.json({ upgrade: await getRuntimeUpgradeForProject(access.project.id, upgradeId) }); } catch (error) { return errorResponse(error, "Unable to read runtime upgrade."); } }
export async function POST(request: Request, context: { params: Promise<{ id: string; upgradeId: string }> }) { try { const access = await authorize(request, context); if (access.response) return access.response; const { upgradeId } = await context.params; const body = await request.json().catch(() => ({})); if (body.action === "accept") return Response.json({ upgrade: await acceptStoredRuntimeUpgrade(access.project, upgradeId, body.acknowledgeWarnings === true) }); if (body.action === "cancel") return Response.json({ upgrade: await cancelStoredRuntimeUpgrade(access.project.id, upgradeId) }); return Response.json({ error: "Runtime upgrade action must be accept or cancel." }, { status: 400 }); } catch (error) { return errorResponse(error, "Unable to update runtime upgrade."); } }
async function authorize(request: Request, context: { params: Promise<{ id: string; upgradeId: string }> }) { const auth = await requireEditorAuth(request); if (auth) return { response: auth }; const principal = getProjectPrincipal(request); if (!principal) return { response: principalRequiredResponse() }; const { id } = await context.params; const project = await getProject(id); if (!project || project.status === "deleted") return { response: Response.json({ error: "Project was not found." }, { status: 404 }) }; if (!canEditProject(project, principal)) return { response: projectAccessResponse() }; return { project }; }
function errorResponse(error: unknown, fallback: string) { const status = error instanceof RuntimeUpgradeStoreError ? error.status : 500; return Response.json({ error: error instanceof Error ? error.message : fallback }, { status }); }
