import { requireEditorAuth } from "@/lib/api-auth";
import { canEditProject, getProjectPrincipal, principalRequiredResponse, projectAccessResponse } from "@/lib/project-access";
import { getProject } from "@/lib/projects";
import { acceptMediaJob, cancelMediaJob, discardMediaJob, getMediaJobForProject, retryMediaJob, MediaJobStoreError } from "@/lib/media-job-manager.mjs";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
export async function GET(request: Request, context: { params: Promise<{ id: string; jobId: string }> }) { try { const access = await authorize(request, context); if (access.response) return access.response; const { jobId } = await context.params; return Response.json({ job: await getMediaJobForProject(access.project.id, jobId) }); } catch (error) { return errorResponse(error, "Unable to read media job."); } }
export async function POST(request: Request, context: { params: Promise<{ id: string; jobId: string }> }) { try { const access = await authorize(request, context); if (access.response) return access.response; const { jobId } = await context.params; const body = await request.json().catch(() => ({})); if (body.action === "accept") return Response.json({ job: await acceptMediaJob(access.project, jobId, body.metadata || null) }); if (body.action === "discard") return Response.json({ job: await discardMediaJob(access.project.id, jobId) }); if (body.action === "cancel") return Response.json({ job: await cancelMediaJob(access.project.id, jobId) }); if (body.action === "retry") return Response.json({ job: await retryMediaJob(access.project, getProjectPrincipal(request)!, jobId) }); return Response.json({ error: "Media job action must be accept, discard, cancel, or retry." }, { status: 400 }); } catch (error) { return errorResponse(error, "Unable to update media job."); } }
async function authorize(request: Request, context: { params: Promise<{ id: string; jobId: string }> }) { const auth = await requireEditorAuth(request); if (auth) return { response: auth }; const principal = getProjectPrincipal(request); if (!principal) return { response: principalRequiredResponse() }; const { id } = await context.params; const project = await getProject(id); if (!project || project.status === "deleted") return { response: Response.json({ error: "Project was not found." }, { status: 404 }) }; if (!canEditProject(project, principal)) return { response: projectAccessResponse() }; return { project }; }
function errorResponse(error: unknown, fallback: string) { const status = error instanceof MediaJobStoreError ? error.status : 500; return Response.json({ error: error instanceof Error ? error.message : fallback }, { status }); }
