import { requireEditorAuth } from "@/lib/api-auth";
import { canEditProject, getProjectPrincipal, principalRequiredResponse, projectAccessResponse } from "@/lib/project-access";
import { getProject } from "@/lib/projects";
import { listMediaJobs, startMediaJob, MediaJobStoreError } from "@/lib/media-job-manager.mjs";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
export async function GET(request: Request, context: { params: Promise<{ id: string }> }) { try { const access = await authorize(request, context); if (access.response) return access.response; return Response.json({ jobs: await listMediaJobs(access.project.id) }, { headers: { "Cache-Control": "no-store" } }); } catch (error) { return errorResponse(error, "Unable to list media jobs."); } }
export async function POST(request: Request, context: { params: Promise<{ id: string }> }) { try { const access = await authorize(request, context); if (access.response) return access.response; const body = await request.json().catch(() => ({})); const principal = getProjectPrincipal(request); return Response.json({ job: await startMediaJob(access.project, principal!, body) }, { status: 202 }); } catch (error) { return errorResponse(error, "Unable to start media job."); } }
async function authorize(request: Request, context: { params: Promise<{ id: string }> }) { const auth = await requireEditorAuth(request); if (auth) return { response: auth }; const principal = getProjectPrincipal(request); if (!principal) return { response: principalRequiredResponse() }; const { id } = await context.params; const project = await getProject(id); if (!project || project.status === "deleted") return { response: Response.json({ error: "Project was not found." }, { status: 404 }) }; if (!canEditProject(project, principal)) return { response: projectAccessResponse() }; return { project }; }
function errorResponse(error: unknown, fallback: string) { const status = error instanceof MediaJobStoreError ? error.status : 500; return Response.json({ error: error instanceof Error ? error.message : fallback }, { status }); }
